### ISSUE TITLE
Broken on modern python

### ISSUE THREAD

**Issue by fake-name** [ericfreese/font-viewer#22]
```


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Python35\python.EXE" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\durr\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\durr\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\durr\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\durr\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\durr\AppData\Local\Temp\apm-install-dir-11887-2264-f69vg2.yxpiffajor\node_modules\font-viewer\node_modules\freetype2
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\durr\AppData\Local\Temp\apm-install-dir-11887-2264-f69vg2.yxpiffajor\package.json'
npm WARN apm-install-dir-11887-2264-f69vg2.yxpiffajor No description
npm WARN apm-install-dir-11887-2264-f69vg2.yxpiffajor No repository field.
npm WARN apm-install-dir-11887-2264-f69vg2.yxpiffajor No README data
npm WARN apm-install-dir-11887-2264-f69vg2.yxpiffajor No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\durr\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\durr\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\durr\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\durr\\.atom\\.apmrc" "install" "C:\\Users\\durr\\AppData\\Local\\Temp\\d-11887-2264-1mfg46z.c6yz99hpvi\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! freetype2@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freetype2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freetype2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freetype2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\durr\AppData\Local\Temp\apm-install-dir-11887-2264-f69vg2.yxpiffajor\npm-debug.log
npm ERR! code 1

```

Py2k is dead. 

(Title rename because I mis-read the error output)

**Comment by ericfreese** [comment]
See #18

**Comment by fake-name** [comment]
Oh, ok. Sorry about that.

**Comment by ericfreese** [comment]
We can keep the issue open. Just making clear I don't maintain this anymore so I won't personally be fixing this. I'm looking for someone to take it over going forward.

**Comment by fake-name** [comment]
Ah, ok. 

As a stand in, maybe mention the lack of maintenance on [the homepage](https://github.com/ericfreese/font-viewer)? And ideally in the [atom package listing](https://atom.io/packages/font-viewer) too?
